#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH=$PATH:/usr/local/Cellar/mysql-client/8.0.32/bin

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/koji/work/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/koji/work/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/koji/work/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/koji/work/google-cloud-sdk/completion.zsh.inc'; fi

eval "$(direnv hook zsh)"

# Created by `pipx` on 2023-05-14 00:15:53
export PATH="$PATH:/Users/koji/.local/bin"
